# Generated by Django 3.1.7 on 2021-05-04 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.CharField(help_text='Required and Unique', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='prodcut id ')),
                ('title', models.CharField(help_text='Required ', max_length=20, verbose_name='Product Name ')),
                ('product_link', models.URLField(help_text='The product website or link', max_length=255, verbose_name='Product Url')),
                ('tagline', models.CharField(help_text='describe in short of your product', max_length=255, verbose_name='small product description')),
                ('description', models.TextField(help_text='Describe in long of your product', max_length=500, verbose_name='long product description')),
                ('upvote', models.IntegerField(default=0, verbose_name='product upvote ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('launch_at', models.DateTimeField(auto_now_add=True, verbose_name='Launch at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Creator ')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('image', models.URLField(help_text='Product screenshot images ', verbose_name='Product image ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='api.product', verbose_name='product Id')),
            ],
        ),
        migrations.CreateModel(
            name='ProductIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(help_text='Product profile images ,logo, icons  ', verbose_name='Product profile image ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_icon', to='api.product', verbose_name='product ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Comment made to prouct ', max_length=400, verbose_name='Comments text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment', to='api.product', verbose_name='product Id')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Product categories')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.product', verbose_name='product Id')),
            ],
        ),
    ]
