# Generated by Django 3.1.7 on 2021-05-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='launch_at',
            field=models.DateTimeField(verbose_name='Launch at'),
        ),
    ]
