# Generated by Django 3.1.7 on 2021-04-02 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcutID',
            new_name='productID',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pasword',
            new_name='password',
        ),
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.URLField(default=django.utils.timezone.now, help_text='The product website or link', max_length=255, verbose_name='Product Url'),
            preserve_default=False,
        ),
    ]
