# Generated by Django 3.1.7 on 2021-05-06 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productupvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='productupvote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
