# Generated by Django 3.1.7 on 2021-04-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210402_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile_image',
            field=models.ForeignKey(default='default.png', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profileimage', verbose_name='Product icon or logo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ForeignKey(default='default.png', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profileimage', verbose_name='User Profile Image '),
        ),
    ]
