# Generated by Django 3.1.7 on 2021-05-06 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_productupvote_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productupvote',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to=settings.AUTH_USER_MODEL, verbose_name='user id '),
        ),
    ]
