# Generated by Django 3.1.7 on 2021-05-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210506_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Describe in long of your product', max_length=800, verbose_name='long product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productID',
            field=models.CharField(help_text='Required and Unique', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='prodcut id '),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.URLField(help_text='The product website or link', verbose_name='Product Url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Required ', max_length=50, verbose_name='Product Name '),
        ),
    ]
