# Generated by Django 3.1.7 on 2021-04-27 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210422_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(help_text='Product profile images ,logo, icons  ', verbose_name='Product profile image ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='upvote',
            field=models.IntegerField(default=0, verbose_name='product upvote '),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(help_text='Product screenshot images ', verbose_name='Product image '),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
        migrations.AddField(
            model_name='producticon',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='product Id'),
        ),
    ]
