# Generated by Django 3.1.7 on 2021-04-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210422_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile_image',
            field=models.URLField(null=True, verbose_name='Product icon or logo'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(help_text='Product screenshot images ', verbose_name='Product image '),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.URLField(help_text='Product profile images ,logo, icons  ', verbose_name='Product profile image '),
        ),
    ]
