# Generated by Django 3.1.7 on 2021-04-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_auto_20210425_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_image',
            field=models.CharField(max_length=500, verbose_name=' Profile image url '),
        ),
    ]
